### ISSUE TITLE
BBMD and Docker

### ISSUE THREAD

**Issue by AlexMAS** [bacnet-stack/bacnet-stack#224]
Hello!

First of all, thanks for your project!

I have a question about using BBMD functionality.

Currently to test BACnet I run `backnet-stack` in Docker and it works fine.

**docker-compose.yml**
```yml
ersion: '3.7'

services:

  # Defines the virtual BACnet device
  bacnet_device:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bacnet
    container_name: bacnet_device
    command: bacserv 200001
    networks:
      - dev
```

**Dockerfile**
```Dockerfile
FROM ubuntu:20.04 AS build

RUN apt-get update && apt-get -y install build-essential

WORKDIR /bacnet-stack
COPY bacnet-stack ./
RUN make

FROM ubuntu:20.04 AS runtime

COPY --from=build /bacnet-stack/bin/* /usr/local/bin/
ADD bacnet-wrapper /

RUN chmod a+x /bacnet-wrapper

EXPOSE 47808:47808/udp

CMD ["/bacnet-wrapper"]
```

**bacnet-wrapper**
```bash
#!/bin/bash

bin=/usr/local/bin

# if ($1 != "" && fileExists($bin/$1) && fileExecutable($bin/$1))
if [[ x"$1" != x && -f $bin/$1 && -x $bin/$1 ]]; then
    exec $@
else
    echo 'Usage: docker run -it bacnet <command> <args>'
    echo '... where <command> is one of:'
    ls -C $bin
    exit 1
fi
```

To development we just added this container to our project network.

But in production environment we have to work with BACnet devices by using BBMD. And now we would like to setup a test environment like we have to check that our app works fine. I suppose that we need to do the next steps.

* Run `bacserv` in one Docker container (like above mentioned) in one network (let's say `net1`)
* Run a BBMD gateway in the app network (that's the question - I don't know how to do it)
* Register the virtual device from `net1` in the BBMD gateway (also the question)

I'm not so familiar with BACnet and to be honest understand only base principles of the protocol :)

Thanks!
